### ISSUE TITLE
IDs need be within the range he specified, 1 billion to 1,001,000,000

### ISSUE THREAD

**Issue by joeflack4** [HOT-Ecosystem/ValueSet-Tools#26]
## Tasks
- [ ] 1. Create logic to create IDs within range of "1 billion to 1,001,000,000"
- [ ] 2. Figure out an area where this needs to be stored
- [ ] 3. Utilize this ID as the primary key that links concept sets between the 3 API calls

**Comment by joeflack4** [comment]
So far I've done this statically, in: `data/oids_enclaveId.csv`

But we need a more permanent way to do this.

**Comment by joeflack4** [comment]
For (2), we discussed that this could be a Heroku DB.

**Comment by joeflack4** [comment]
Instead of pre-assigning our IDs, we're now allowing the system to auto-assign IDs for us.
