### ISSUE TITLE
Value set name collisions

### ISSUE THREAD

**Issue by joeflack4** [HOT-Ecosystem/ValueSet-Tools#30]
## Description
(@stephanieshong Please feel free to edit this and change this text if I got anything wrong.)
There are some edge cases where we have value sets with the same name. And sometimes there is a single OID which represents a grouping of those value sets. And, in a smaller subset of those edge cases, there is no such OID / value set on UMLS.

In those cases, we should create a new grouping value set:
- Create to be uploaded in enclave. We don't need to make in UMLS.
- Will not have an OID
- Members of the concept set should be all the members of all of the value sets with the same name.
- Provenance should include the OIDs of those value sets.

## Tasks
- [x] 1. Update our code to revert the changes we made (the appending of code systems to the value set names).
- [ ] 2. Handle collision cases
  - [x] 2.a. Use existing grouping sets that exist.
  - [ ] 2.b. Handle cases where there isn't an existing grouping set.

## Task 2 Options
Option **(d)** seems to be the best, based on our discussion at the 2022/02/17 BIDS data meeting.

### ~a. Merge the value sets~
I think this assumes that the value sets that would be merged are of entirely different code systems. I suppose we can work with that assumption for now, but if that isn't the case, we'll need to think about what to do. This one seems preferred.

### ~b. Give the value sets different names~
This is what we've already done. We decided to append code system names to the value set. But it seems this is not preferred.

### ~c. Only upload 1 of the value sets~
I this is the case, we'd need to store information about the value set collisions to some data storage layer (file or DB). Then wed need a curation process to determine which set is best.

### d. Create a new set **_(when grouping not available)_**
1. _**Optional**_: Create new set in VSAC and get OID: https://www.nlm.nih.gov/vsac/support/authorguidelines/createvs.html (edit: We decided this doesn't need to be done)
2. _**Optional**_: Add new OID to `cset.csv` (only if we do (1))
3. Update code to programmatically create new sets in these collision cases where no grouping already exists.
4. Upload to enclave
5. _**Optional**_: Register IDs? (options: [a](http://www.hl7.org/OID/), [b](https://www.doi.org/)) (only if we do (1))
  - Davera mentioned this, but I'm not sure it's necessary, as VSAC autogenerates new OIDs (step 1 above). HL7 also charges $500 to register an OID.

### e. Use previously created combination value sets / OIDs **_(when grouping set available)_**
A "grouping set" is when a value set is defined as a "grouping" in UMLS VSAC, and its members are OIDs that point to its composite value sets.

Apparently, for some (or perhaps all?) instances of value sets which have more than 1 instance in VSAC, there exist other value sets which have grouped these multiple instances together. I believe this is mainly to account for different code systems. So, for example, there may be a value sets for blood transfusion. There may be a set that is (i) in one code system (e.g. SNOMED) and another that uses (ii) a different code system (e.g. ICD10CM). Then, there may be a (iii) 3rd value set which combines the codes with both. In this case, what we we want to do is to use and upload (iii) to the enclave, and not upload (i) and (ii).

We should use this option (e) as much as possible, and only use option (d) (creating a new value set) if VSAC doesn't already have such a grouped value set.

**Comment by stephanieshong** [comment]
According to what @Davera mentioned, she would prefer the following, but we can chat more during our meeting today.
1. remove the code system from the name.
2. combine the two oids to one concept set
3. update the provenance to include two oids and the code system
4

**Comment by joeflack4** [comment]
Just commenting that we've moved from preference towards option **(a)** (Stephanie's previous comment) to option **(d)**.

**Comment by joeflack4** [comment]
@stephanieshong Based on what you told me on Teams today, I created a new option (e) above:
> e. Use previously created combination value sets / OIDs (1st best choice)

**Comment by joeflack4** [comment]
Additional decisions were made, and written down in our BIDS strategy meeting agenda notes, 2/23/2022: https://docs.google.com/document/d/1ojHRjh_IWItT4xul1z1XaHzDQPctOUCe/edit#

**Comment by stephanieshong** [comment]
Your 3 csv files is not usable, as they are used to build the JSON structures need to call the RESTAPI call in the Enclave.

**Comment by stephanieshong** [comment]
concept_set_id is used as a key in the Enclave and it cannot be a numerical value. We are using concept set name as the concept_set_id.
I am reopening this issue.

**Comment by stephanieshong** [comment]
assigning this issue to 
@stephanieshong and @joeflack4

**Comment by joeflack4** [comment]
I updated the OP (original post) today.

**Comment by stephanieshong** [comment]
assigned to @stephanieshong - For edge cases where we are missing the Grouped OIDs from VSAC, 
1. create a grouped version in the Enclave, remove the code system from the name as we had it before.
2. combine the two OIDs to one concept set and update the code System info to include both
3. update the provenance to include two OIDs and the code system from VSAC

**Comment by stephanieshong** [comment]
Chris over ruled and requested not to include the grouped OIDs.
