### ISSUE TITLE
ValueSet-Tools: Validation/QC: Run after uploads

### ISSUE THREAD

**Issue by joeflack4** [HOT-Ecosystem/ValueSet-Tools#57]
## Description
@Sigfried has added some validation code that can check the quality of concept sets we've previously uploaded to the enclave.

What this issue proposes is to run this code, or similar code, immediately after the `enclave_wrangler` does its uploads.

## Tasks
- [ ] 1. Decide what checks to run
- [ ] 2. Implement them / merge code w/ Siggie's existing validation code
- [ ] 3. Make sure it runs after uploads
- [ ] 4. What to do after? Just generate a report? Or do a `DELETE` on any concept sets that we uploaded but turned out to be problematic?
