### ISSUE TITLE
graphviz & dot

### ISSUE THREAD

**Issue by joeflack4** [HOT-Ecosystem/ValueSet-Tools#670]
## Overview
Siggie has started using `graphviz` and the declarative `dot` language. `dot` is for declaring graphs, and there are tools associated with that. `graphviz` can create diagrams based on such graphs.

The primary value here, Joe thinks, is that (i) `dot` might simplify some of our graph declaration / manipulations / queries, (ii) `graphviz` might help us to inspect / understand / troubleshoot certain things better.

## Sub-task list
- [ ] 1. Use cases for `dot`
- [ ] 2. Internal development / documentation use cases for `graphviz`
- [ ] 3. User-facing `graphviz` features

### 3. User-facing `graphviz` features
Siggie felt it would be good to have such diagrams as a feature for users. Joe thinks this is a low priority task

Doing such would require us to deploy TermHub and install graphviz through Python as part of that pipeline and possibly also commit or install additional executables which it requires.

Also, OAK uses `graphviz`. Maybe there's something from OAK we can learn / leverage?
